import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import styles from "./globals.css"
export const metadata = {
  title: "PUSG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles}><Navbar/>{children}<Footer/></body>
    </html>
  );
}
